// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/model/service/migration (interfaces: State)
//
// Generated by this command:
//
//	mockgen -typed -package migration -destination package_mock_test.go github.com/juju/juju/domain/model/service/migration State
//

// Package migration is a generated GoMock package.
package migration

import (
	context "context"
	reflect "reflect"

	cloud "github.com/juju/juju/cloud"
	model "github.com/juju/juju/core/model"
	model0 "github.com/juju/juju/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockState) Activate(arg0 context.Context, arg1 model.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockStateMockRecorder) Activate(arg0, arg1 any) *MockStateActivateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockState)(nil).Activate), arg0, arg1)
	return &MockStateActivateCall{Call: call}
}

// MockStateActivateCall wrap *gomock.Call
type MockStateActivateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateActivateCall) Return(arg0 error) *MockStateActivateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateActivateCall) Do(f func(context.Context, model.UUID) error) *MockStateActivateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateActivateCall) DoAndReturn(f func(context.Context, model.UUID) error) *MockStateActivateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloudSupportsAuthType mocks base method.
func (m *MockState) CloudSupportsAuthType(arg0 context.Context, arg1 string, arg2 cloud.AuthType) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudSupportsAuthType", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloudSupportsAuthType indicates an expected call of CloudSupportsAuthType.
func (mr *MockStateMockRecorder) CloudSupportsAuthType(arg0, arg1, arg2 any) *MockStateCloudSupportsAuthTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudSupportsAuthType", reflect.TypeOf((*MockState)(nil).CloudSupportsAuthType), arg0, arg1, arg2)
	return &MockStateCloudSupportsAuthTypeCall{Call: call}
}

// MockStateCloudSupportsAuthTypeCall wrap *gomock.Call
type MockStateCloudSupportsAuthTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateCloudSupportsAuthTypeCall) Return(arg0 bool, arg1 error) *MockStateCloudSupportsAuthTypeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateCloudSupportsAuthTypeCall) Do(f func(context.Context, string, cloud.AuthType) (bool, error)) *MockStateCloudSupportsAuthTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateCloudSupportsAuthTypeCall) DoAndReturn(f func(context.Context, string, cloud.AuthType) (bool, error)) *MockStateCloudSupportsAuthTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloudType mocks base method.
func (m *MockState) CloudType(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudType", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloudType indicates an expected call of CloudType.
func (mr *MockStateMockRecorder) CloudType(arg0, arg1 any) *MockStateCloudTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudType", reflect.TypeOf((*MockState)(nil).CloudType), arg0, arg1)
	return &MockStateCloudTypeCall{Call: call}
}

// MockStateCloudTypeCall wrap *gomock.Call
type MockStateCloudTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateCloudTypeCall) Return(arg0 string, arg1 error) *MockStateCloudTypeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateCloudTypeCall) Do(f func(context.Context, string) (string, error)) *MockStateCloudTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateCloudTypeCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockStateCloudTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockState) Create(arg0 context.Context, arg1 model.UUID, arg2 model.ModelType, arg3 model0.GlobalModelCreationArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStateMockRecorder) Create(arg0, arg1, arg2, arg3 any) *MockStateCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockState)(nil).Create), arg0, arg1, arg2, arg3)
	return &MockStateCreateCall{Call: call}
}

// MockStateCreateCall wrap *gomock.Call
type MockStateCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateCreateCall) Return(arg0 error) *MockStateCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateCreateCall) Do(f func(context.Context, model.UUID, model.ModelType, model0.GlobalModelCreationArgs) error) *MockStateCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateCreateCall) DoAndReturn(f func(context.Context, model.UUID, model.ModelType, model0.GlobalModelCreationArgs) error) *MockStateCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ImportModel mocks base method.
func (m *MockState) ImportModel(arg0 context.Context, arg1 model.UUID, arg2 model.ModelType, arg3 model0.GlobalModelCreationArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportModel", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportModel indicates an expected call of ImportModel.
func (mr *MockStateMockRecorder) ImportModel(arg0, arg1, arg2, arg3 any) *MockStateImportModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportModel", reflect.TypeOf((*MockState)(nil).ImportModel), arg0, arg1, arg2, arg3)
	return &MockStateImportModelCall{Call: call}
}

// MockStateImportModelCall wrap *gomock.Call
type MockStateImportModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateImportModelCall) Return(arg0 error) *MockStateImportModelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateImportModelCall) Do(f func(context.Context, model.UUID, model.ModelType, model0.GlobalModelCreationArgs) error) *MockStateImportModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateImportModelCall) DoAndReturn(f func(context.Context, model.UUID, model.ModelType, model0.GlobalModelCreationArgs) error) *MockStateImportModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
