// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/apiserver/facades/client/highavailability (interfaces: ControllerNodeService)
//
// Generated by this command:
//
//	mockgen -typed -package highavailability -destination service_mock_test.go github.com/juju/juju/apiserver/facades/client/highavailability ControllerNodeService
//

// Package highavailability is a generated GoMock package.
package highavailability

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockControllerNodeService is a mock of ControllerNodeService interface.
type MockControllerNodeService struct {
	ctrl     *gomock.Controller
	recorder *MockControllerNodeServiceMockRecorder
}

// MockControllerNodeServiceMockRecorder is the mock recorder for MockControllerNodeService.
type MockControllerNodeServiceMockRecorder struct {
	mock *MockControllerNodeService
}

// NewMockControllerNodeService creates a new mock instance.
func NewMockControllerNodeService(ctrl *gomock.Controller) *MockControllerNodeService {
	mock := &MockControllerNodeService{ctrl: ctrl}
	mock.recorder = &MockControllerNodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerNodeService) EXPECT() *MockControllerNodeServiceMockRecorder {
	return m.recorder
}

// GetAPIAddressesByControllerIDForClients mocks base method.
func (m *MockControllerNodeService) GetAPIAddressesByControllerIDForClients(arg0 context.Context) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIAddressesByControllerIDForClients", arg0)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIAddressesByControllerIDForClients indicates an expected call of GetAPIAddressesByControllerIDForClients.
func (mr *MockControllerNodeServiceMockRecorder) GetAPIAddressesByControllerIDForClients(arg0 any) *MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIAddressesByControllerIDForClients", reflect.TypeOf((*MockControllerNodeService)(nil).GetAPIAddressesByControllerIDForClients), arg0)
	return &MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall{Call: call}
}

// MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall wrap *gomock.Call
type MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall) Return(arg0 map[string][]string, arg1 error) *MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall) Do(f func(context.Context) (map[string][]string, error)) *MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall) DoAndReturn(f func(context.Context) (map[string][]string, error)) *MockControllerNodeServiceGetAPIAddressesByControllerIDForClientsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
