// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/worker/apiremotecaller (interfaces: APIRemoteSubscriber,Subscription,RemoteConnection)
//
// Generated by this command:
//
//	mockgen -typed -package controllerpresence -destination caller_mocks_test.go github.com/juju/juju/internal/worker/apiremotecaller APIRemoteSubscriber,Subscription,RemoteConnection
//

// Package controllerpresence is a generated GoMock package.
package controllerpresence

import (
	context "context"
	reflect "reflect"

	api "github.com/juju/juju/api"
	apiremotecaller "github.com/juju/juju/internal/worker/apiremotecaller"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIRemoteSubscriber is a mock of APIRemoteSubscriber interface.
type MockAPIRemoteSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockAPIRemoteSubscriberMockRecorder
}

// MockAPIRemoteSubscriberMockRecorder is the mock recorder for MockAPIRemoteSubscriber.
type MockAPIRemoteSubscriberMockRecorder struct {
	mock *MockAPIRemoteSubscriber
}

// NewMockAPIRemoteSubscriber creates a new mock instance.
func NewMockAPIRemoteSubscriber(ctrl *gomock.Controller) *MockAPIRemoteSubscriber {
	mock := &MockAPIRemoteSubscriber{ctrl: ctrl}
	mock.recorder = &MockAPIRemoteSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIRemoteSubscriber) EXPECT() *MockAPIRemoteSubscriberMockRecorder {
	return m.recorder
}

// GetAPIRemotes mocks base method.
func (m *MockAPIRemoteSubscriber) GetAPIRemotes() ([]apiremotecaller.RemoteConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIRemotes")
	ret0, _ := ret[0].([]apiremotecaller.RemoteConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIRemotes indicates an expected call of GetAPIRemotes.
func (mr *MockAPIRemoteSubscriberMockRecorder) GetAPIRemotes() *MockAPIRemoteSubscriberGetAPIRemotesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIRemotes", reflect.TypeOf((*MockAPIRemoteSubscriber)(nil).GetAPIRemotes))
	return &MockAPIRemoteSubscriberGetAPIRemotesCall{Call: call}
}

// MockAPIRemoteSubscriberGetAPIRemotesCall wrap *gomock.Call
type MockAPIRemoteSubscriberGetAPIRemotesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRemoteSubscriberGetAPIRemotesCall) Return(arg0 []apiremotecaller.RemoteConnection, arg1 error) *MockAPIRemoteSubscriberGetAPIRemotesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRemoteSubscriberGetAPIRemotesCall) Do(f func() ([]apiremotecaller.RemoteConnection, error)) *MockAPIRemoteSubscriberGetAPIRemotesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRemoteSubscriberGetAPIRemotesCall) DoAndReturn(f func() ([]apiremotecaller.RemoteConnection, error)) *MockAPIRemoteSubscriberGetAPIRemotesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Subscribe mocks base method.
func (m *MockAPIRemoteSubscriber) Subscribe() (apiremotecaller.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(apiremotecaller.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockAPIRemoteSubscriberMockRecorder) Subscribe() *MockAPIRemoteSubscriberSubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAPIRemoteSubscriber)(nil).Subscribe))
	return &MockAPIRemoteSubscriberSubscribeCall{Call: call}
}

// MockAPIRemoteSubscriberSubscribeCall wrap *gomock.Call
type MockAPIRemoteSubscriberSubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRemoteSubscriberSubscribeCall) Return(arg0 apiremotecaller.Subscription, arg1 error) *MockAPIRemoteSubscriberSubscribeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRemoteSubscriberSubscribeCall) Do(f func() (apiremotecaller.Subscription, error)) *MockAPIRemoteSubscriberSubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRemoteSubscriberSubscribeCall) DoAndReturn(f func() (apiremotecaller.Subscription, error)) *MockAPIRemoteSubscriberSubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSubscription is a mock of Subscription interface.
type MockSubscription struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionMockRecorder
}

// MockSubscriptionMockRecorder is the mock recorder for MockSubscription.
type MockSubscriptionMockRecorder struct {
	mock *MockSubscription
}

// NewMockSubscription creates a new mock instance.
func NewMockSubscription(ctrl *gomock.Controller) *MockSubscription {
	mock := &MockSubscription{ctrl: ctrl}
	mock.recorder = &MockSubscriptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscription) EXPECT() *MockSubscriptionMockRecorder {
	return m.recorder
}

// Changes mocks base method.
func (m *MockSubscription) Changes() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changes")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Changes indicates an expected call of Changes.
func (mr *MockSubscriptionMockRecorder) Changes() *MockSubscriptionChangesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changes", reflect.TypeOf((*MockSubscription)(nil).Changes))
	return &MockSubscriptionChangesCall{Call: call}
}

// MockSubscriptionChangesCall wrap *gomock.Call
type MockSubscriptionChangesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriptionChangesCall) Return(arg0 <-chan struct{}) *MockSubscriptionChangesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriptionChangesCall) Do(f func() <-chan struct{}) *MockSubscriptionChangesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriptionChangesCall) DoAndReturn(f func() <-chan struct{}) *MockSubscriptionChangesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockSubscription) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSubscriptionMockRecorder) Close() *MockSubscriptionCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSubscription)(nil).Close))
	return &MockSubscriptionCloseCall{Call: call}
}

// MockSubscriptionCloseCall wrap *gomock.Call
type MockSubscriptionCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriptionCloseCall) Return() *MockSubscriptionCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriptionCloseCall) Do(f func()) *MockSubscriptionCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriptionCloseCall) DoAndReturn(f func()) *MockSubscriptionCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRemoteConnection is a mock of RemoteConnection interface.
type MockRemoteConnection struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteConnectionMockRecorder
}

// MockRemoteConnectionMockRecorder is the mock recorder for MockRemoteConnection.
type MockRemoteConnectionMockRecorder struct {
	mock *MockRemoteConnection
}

// NewMockRemoteConnection creates a new mock instance.
func NewMockRemoteConnection(ctrl *gomock.Controller) *MockRemoteConnection {
	mock := &MockRemoteConnection{ctrl: ctrl}
	mock.recorder = &MockRemoteConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteConnection) EXPECT() *MockRemoteConnectionMockRecorder {
	return m.recorder
}

// Connection mocks base method.
func (m *MockRemoteConnection) Connection(arg0 context.Context, arg1 func(context.Context, api.Connection) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connection indicates an expected call of Connection.
func (mr *MockRemoteConnectionMockRecorder) Connection(arg0, arg1 any) *MockRemoteConnectionConnectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connection", reflect.TypeOf((*MockRemoteConnection)(nil).Connection), arg0, arg1)
	return &MockRemoteConnectionConnectionCall{Call: call}
}

// MockRemoteConnectionConnectionCall wrap *gomock.Call
type MockRemoteConnectionConnectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRemoteConnectionConnectionCall) Return(arg0 error) *MockRemoteConnectionConnectionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRemoteConnectionConnectionCall) Do(f func(context.Context, func(context.Context, api.Connection) error) error) *MockRemoteConnectionConnectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRemoteConnectionConnectionCall) DoAndReturn(f func(context.Context, func(context.Context, api.Connection) error) error) *MockRemoteConnectionConnectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ControllerID mocks base method.
func (m *MockRemoteConnection) ControllerID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ControllerID indicates an expected call of ControllerID.
func (mr *MockRemoteConnectionMockRecorder) ControllerID() *MockRemoteConnectionControllerIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerID", reflect.TypeOf((*MockRemoteConnection)(nil).ControllerID))
	return &MockRemoteConnectionControllerIDCall{Call: call}
}

// MockRemoteConnectionControllerIDCall wrap *gomock.Call
type MockRemoteConnectionControllerIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRemoteConnectionControllerIDCall) Return(arg0 string) *MockRemoteConnectionControllerIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRemoteConnectionControllerIDCall) Do(f func() string) *MockRemoteConnectionControllerIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRemoteConnectionControllerIDCall) DoAndReturn(f func() string) *MockRemoteConnectionControllerIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
