// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/worker/controllerpresence (interfaces: ControllerDomainServices,DomainServices,ModelService,StatusService)
//
// Generated by this command:
//
//	mockgen -typed -package controllerpresence -destination package_mocks_test.go github.com/juju/juju/internal/worker/controllerpresence ControllerDomainServices,DomainServices,ModelService,StatusService
//

// Package controllerpresence is a generated GoMock package.
package controllerpresence

import (
	context "context"
	reflect "reflect"

	machine "github.com/juju/juju/core/machine"
	model "github.com/juju/juju/core/model"
	unit "github.com/juju/juju/core/unit"
	gomock "go.uber.org/mock/gomock"
)

// MockControllerDomainServices is a mock of ControllerDomainServices interface.
type MockControllerDomainServices struct {
	ctrl     *gomock.Controller
	recorder *MockControllerDomainServicesMockRecorder
}

// MockControllerDomainServicesMockRecorder is the mock recorder for MockControllerDomainServices.
type MockControllerDomainServicesMockRecorder struct {
	mock *MockControllerDomainServices
}

// NewMockControllerDomainServices creates a new mock instance.
func NewMockControllerDomainServices(ctrl *gomock.Controller) *MockControllerDomainServices {
	mock := &MockControllerDomainServices{ctrl: ctrl}
	mock.recorder = &MockControllerDomainServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerDomainServices) EXPECT() *MockControllerDomainServicesMockRecorder {
	return m.recorder
}

// Model mocks base method.
func (m *MockControllerDomainServices) Model() ModelService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Model")
	ret0, _ := ret[0].(ModelService)
	return ret0
}

// Model indicates an expected call of Model.
func (mr *MockControllerDomainServicesMockRecorder) Model() *MockControllerDomainServicesModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Model", reflect.TypeOf((*MockControllerDomainServices)(nil).Model))
	return &MockControllerDomainServicesModelCall{Call: call}
}

// MockControllerDomainServicesModelCall wrap *gomock.Call
type MockControllerDomainServicesModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerDomainServicesModelCall) Return(arg0 ModelService) *MockControllerDomainServicesModelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerDomainServicesModelCall) Do(f func() ModelService) *MockControllerDomainServicesModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerDomainServicesModelCall) DoAndReturn(f func() ModelService) *MockControllerDomainServicesModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDomainServices is a mock of DomainServices interface.
type MockDomainServices struct {
	ctrl     *gomock.Controller
	recorder *MockDomainServicesMockRecorder
}

// MockDomainServicesMockRecorder is the mock recorder for MockDomainServices.
type MockDomainServicesMockRecorder struct {
	mock *MockDomainServices
}

// NewMockDomainServices creates a new mock instance.
func NewMockDomainServices(ctrl *gomock.Controller) *MockDomainServices {
	mock := &MockDomainServices{ctrl: ctrl}
	mock.recorder = &MockDomainServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainServices) EXPECT() *MockDomainServicesMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockDomainServices) Status() StatusService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(StatusService)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockDomainServicesMockRecorder) Status() *MockDomainServicesStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockDomainServices)(nil).Status))
	return &MockDomainServicesStatusCall{Call: call}
}

// MockDomainServicesStatusCall wrap *gomock.Call
type MockDomainServicesStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDomainServicesStatusCall) Return(arg0 StatusService) *MockDomainServicesStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDomainServicesStatusCall) Do(f func() StatusService) *MockDomainServicesStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDomainServicesStatusCall) DoAndReturn(f func() StatusService) *MockDomainServicesStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockModelService is a mock of ModelService interface.
type MockModelService struct {
	ctrl     *gomock.Controller
	recorder *MockModelServiceMockRecorder
}

// MockModelServiceMockRecorder is the mock recorder for MockModelService.
type MockModelServiceMockRecorder struct {
	mock *MockModelService
}

// NewMockModelService creates a new mock instance.
func NewMockModelService(ctrl *gomock.Controller) *MockModelService {
	mock := &MockModelService{ctrl: ctrl}
	mock.recorder = &MockModelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelService) EXPECT() *MockModelServiceMockRecorder {
	return m.recorder
}

// GetControllerModelUUID mocks base method.
func (m *MockModelService) GetControllerModelUUID(arg0 context.Context) (model.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControllerModelUUID", arg0)
	ret0, _ := ret[0].(model.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetControllerModelUUID indicates an expected call of GetControllerModelUUID.
func (mr *MockModelServiceMockRecorder) GetControllerModelUUID(arg0 any) *MockModelServiceGetControllerModelUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControllerModelUUID", reflect.TypeOf((*MockModelService)(nil).GetControllerModelUUID), arg0)
	return &MockModelServiceGetControllerModelUUIDCall{Call: call}
}

// MockModelServiceGetControllerModelUUIDCall wrap *gomock.Call
type MockModelServiceGetControllerModelUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelServiceGetControllerModelUUIDCall) Return(arg0 model.UUID, arg1 error) *MockModelServiceGetControllerModelUUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelServiceGetControllerModelUUIDCall) Do(f func(context.Context) (model.UUID, error)) *MockModelServiceGetControllerModelUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelServiceGetControllerModelUUIDCall) DoAndReturn(f func(context.Context) (model.UUID, error)) *MockModelServiceGetControllerModelUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStatusService is a mock of StatusService interface.
type MockStatusService struct {
	ctrl     *gomock.Controller
	recorder *MockStatusServiceMockRecorder
}

// MockStatusServiceMockRecorder is the mock recorder for MockStatusService.
type MockStatusServiceMockRecorder struct {
	mock *MockStatusService
}

// NewMockStatusService creates a new mock instance.
func NewMockStatusService(ctrl *gomock.Controller) *MockStatusService {
	mock := &MockStatusService{ctrl: ctrl}
	mock.recorder = &MockStatusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusService) EXPECT() *MockStatusServiceMockRecorder {
	return m.recorder
}

// DeleteMachinePresence mocks base method.
func (m *MockStatusService) DeleteMachinePresence(arg0 context.Context, arg1 machine.Name) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMachinePresence", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMachinePresence indicates an expected call of DeleteMachinePresence.
func (mr *MockStatusServiceMockRecorder) DeleteMachinePresence(arg0, arg1 any) *MockStatusServiceDeleteMachinePresenceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMachinePresence", reflect.TypeOf((*MockStatusService)(nil).DeleteMachinePresence), arg0, arg1)
	return &MockStatusServiceDeleteMachinePresenceCall{Call: call}
}

// MockStatusServiceDeleteMachinePresenceCall wrap *gomock.Call
type MockStatusServiceDeleteMachinePresenceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatusServiceDeleteMachinePresenceCall) Return(arg0 error) *MockStatusServiceDeleteMachinePresenceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatusServiceDeleteMachinePresenceCall) Do(f func(context.Context, machine.Name) error) *MockStatusServiceDeleteMachinePresenceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatusServiceDeleteMachinePresenceCall) DoAndReturn(f func(context.Context, machine.Name) error) *MockStatusServiceDeleteMachinePresenceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteUnitPresence mocks base method.
func (m *MockStatusService) DeleteUnitPresence(arg0 context.Context, arg1 unit.Name) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnitPresence", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUnitPresence indicates an expected call of DeleteUnitPresence.
func (mr *MockStatusServiceMockRecorder) DeleteUnitPresence(arg0, arg1 any) *MockStatusServiceDeleteUnitPresenceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnitPresence", reflect.TypeOf((*MockStatusService)(nil).DeleteUnitPresence), arg0, arg1)
	return &MockStatusServiceDeleteUnitPresenceCall{Call: call}
}

// MockStatusServiceDeleteUnitPresenceCall wrap *gomock.Call
type MockStatusServiceDeleteUnitPresenceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatusServiceDeleteUnitPresenceCall) Return(arg0 error) *MockStatusServiceDeleteUnitPresenceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatusServiceDeleteUnitPresenceCall) Do(f func(context.Context, unit.Name) error) *MockStatusServiceDeleteUnitPresenceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatusServiceDeleteUnitPresenceCall) DoAndReturn(f func(context.Context, unit.Name) error) *MockStatusServiceDeleteUnitPresenceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
