// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/unitstate/service (interfaces: State)
//
// Generated by this command:
//
//	mockgen -typed -package service -destination state_mock_test.go github.com/juju/juju/domain/unitstate/service State
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	unitstate "github.com/juju/juju/domain/unitstate"
	internal "github.com/juju/juju/domain/unitstate/internal"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// CommitHookChanges mocks base method.
func (m *MockState) CommitHookChanges(arg0 context.Context, arg1 internal.CommitHookChangesArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitHookChanges", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitHookChanges indicates an expected call of CommitHookChanges.
func (mr *MockStateMockRecorder) CommitHookChanges(arg0, arg1 any) *MockStateCommitHookChangesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitHookChanges", reflect.TypeOf((*MockState)(nil).CommitHookChanges), arg0, arg1)
	return &MockStateCommitHookChangesCall{Call: call}
}

// MockStateCommitHookChangesCall wrap *gomock.Call
type MockStateCommitHookChangesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateCommitHookChangesCall) Return(arg0 error) *MockStateCommitHookChangesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateCommitHookChangesCall) Do(f func(context.Context, internal.CommitHookChangesArg) error) *MockStateCommitHookChangesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateCommitHookChangesCall) DoAndReturn(f func(context.Context, internal.CommitHookChangesArg) error) *MockStateCommitHookChangesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUnitState mocks base method.
func (m *MockState) GetUnitState(arg0 context.Context, arg1 string) (unitstate.RetrievedUnitState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitState", arg0, arg1)
	ret0, _ := ret[0].(unitstate.RetrievedUnitState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitState indicates an expected call of GetUnitState.
func (mr *MockStateMockRecorder) GetUnitState(arg0, arg1 any) *MockStateGetUnitStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitState", reflect.TypeOf((*MockState)(nil).GetUnitState), arg0, arg1)
	return &MockStateGetUnitStateCall{Call: call}
}

// MockStateGetUnitStateCall wrap *gomock.Call
type MockStateGetUnitStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateGetUnitStateCall) Return(arg0 unitstate.RetrievedUnitState, arg1 error) *MockStateGetUnitStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateGetUnitStateCall) Do(f func(context.Context, string) (unitstate.RetrievedUnitState, error)) *MockStateGetUnitStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateGetUnitStateCall) DoAndReturn(f func(context.Context, string) (unitstate.RetrievedUnitState, error)) *MockStateGetUnitStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetUnitState mocks base method.
func (m *MockState) SetUnitState(arg0 context.Context, arg1 unitstate.UnitState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUnitState", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUnitState indicates an expected call of SetUnitState.
func (mr *MockStateMockRecorder) SetUnitState(arg0, arg1 any) *MockStateSetUnitStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUnitState", reflect.TypeOf((*MockState)(nil).SetUnitState), arg0, arg1)
	return &MockStateSetUnitStateCall{Call: call}
}

// MockStateSetUnitStateCall wrap *gomock.Call
type MockStateSetUnitStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateSetUnitStateCall) Return(arg0 error) *MockStateSetUnitStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateSetUnitStateCall) Do(f func(context.Context, unitstate.UnitState) error) *MockStateSetUnitStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateSetUnitStateCall) DoAndReturn(f func(context.Context, unitstate.UnitState) error) *MockStateSetUnitStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
